export const RETRIEVE_ALUMNOS = "RETRIEVE_ALUMNOS";
export const UPDATE_ALUMNO = "UPDATE_ALUMNO";
export const CREATE_ALUMNO = "CREATE_ALUMNO";
export const DELETE_ALUMNO = "DELETE_ALUMNO";
export const RETRIEVE_INCIDENCIAS = "RETRIEVE_INCIDENCIAS";
export const CREATE_INCIDENCIA = "CREATE_INCIDENCIA";
export const DELETE_INCIDENCIA = "DELETE_INCIDENCIA";
